defaults: &defaults
  docker:
    - image: opuscapita/minsk-core-ci:4
  working_directory: ~/build

version: 2.1

orbs:
  jira: circleci/jira@1.2.2

jobs:
  init:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:2
    steps:
      - run: circle_ci_add_env.sh GH_MAIL GH_NAME

  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-react-select-{{ .Branch }}-{{ checksum "package.json" }}

      - run: if [ -f /.dockerenv ]; then configure-maven.sh && configure-grails.sh && configure-npm.sh; fi

      - run:
          name: "Installing dependencies."
          command: npm install

      - save_cache:
          key: v3-react-select-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: "Running lint."
          command: npm run lint

      # - run:
      #     name: Test
      #     command: |
      #       mkdir junit
      #       npm test -- --ci --testResultsProcessor='jest-junit-reporter'
      #     environment:
      #       TEST_REPORT_PATH: junit
      #       TEST_REPORT_FILENAME: test-results.xml
      #
      # - store_test_results:
      #     path: junit
      #
      # - store_artifacts:
      #     path: junit

  update-gh-pages:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-react-select-{{ .Branch }}-{{ checksum "package.json" }}

      - run: if [ -f /.dockerenv ]; then configure-maven.sh && configure-grails.sh && configure-npm.sh; fi

      - run:
          name: "Installing dependencies."
          command: npm install

      - save_cache:
          key: v3-react-select-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - ./node_modules

      - run:
          name: deploy-gh-pages
          command: npm run gh-pages-deploy

  build_release:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-react-select-{{ .Branch }}-{{ checksum "package.json" }}

      - run: if [ -f /.dockerenv ]; then configure-maven.sh && configure-grails.sh && configure-npm.sh; fi

      - run:
          name: "Installing dependencies."
          command: npm install

      - save_cache:
          key: v3-react-select-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - ./node_modules

      - run:
          name: "Running lint."
          command: npm run lint

      # - run:
      #     name: Test
      #     command: |
      #       mkdir junit
      #       npm test -- --ci --testResultsProcessor='jest-junit-reporter'
      #     environment:
      #       TEST_REPORT_PATH: junit
      #       TEST_REPORT_FILENAME: test-results.xml
      #
      # - store_test_results:
      #     path: junit
      #
      # - store_artifacts:
      #     path: junit

      - run:
          name: "Deploy."
          command: npm run publish-release

  release:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Executing release scrtipt.
          command: .circleci/release.sh

workflows:
  version: 2
  release-and-build:
    jobs:
      - init:
          filters:
            tags:
              only: /.*/  
      - release:
          filters:
            branches:
              only: release
          requires:
            - init
          post-steps:
            - jira/notify
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
                - release
          requires:
            - init
          post-steps:
            - jira/notify
      - update-gh-pages:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
                - release
      - build_release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - init
          post-steps:
            - jira/notify
